Bicep optimization
itwzhp/bikejamboree pull request #3
Opened 2023-05-04 17:04 UTC by kovansky

Fixe i optymalizacja pliku bicep / @karol-gro

2023-05-04 17:05 UTC, kovansky commented on inreach-parser/inreach-parser.bicep
> +          value: '~14'
Czy w tym miejscu nie dać `~18` dla nowszego Node'a?

2023-05-05 06:38 UTC, karol-gro requested changes

2023-05-05 06:38 UTC, karol-gro commented on inreach-parser/inreach-parser.bicep
> +          value: '~14'
yup, daj 18

2023-05-05 07:54 UTC, kovansky commented on inreach-parser/inreach-parser.bicep
> +          value: '~14'
Zmienione, można mergować

2023-05-05 08:19 UTC, karol-gro approved these changes

2023-05-05 10:46 UTC, merged